### ISSUE TITLE
Unable to update WordPress 5.2.2

### ISSUE THREAD

**Issue by usanuman** [syncloud/wordpress#1]
An automated WordPress update has failed to complete. 

Update WordPress
Downloading update from https://downloads.wordpress.org/release/wordpress-5.2.2-no-content.zip…

Unpacking the update…

The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions.: wp-admin/includes/update-core.php

Installation Failed

**Comment by cyberb** [comment]
Did it break your installation?
We should not really allow auto app update as we want to test it first.
I will try to push updated 5.2.2 version with autoupdate disabled.

**Comment by cyberb** [comment]
I have pushed the updated version.
Please update.
